change speedtest script to "cd" into the folder to archive
apparently using tar or zip with /path/to/files/* causes errors:

Console:
zip I/O error: Permission denied
zip error: Could not create output file
(/pnfs/4/speedtest/8M/100000.zip)

dCacheDomain.log (dcache-lab000)
03 Sep 2013 11:45:03 (billing)
[door:nfsv41@nfs:1378200573206 dcache-lab001-A] 09.03 11:43:52
[pool:dcache-lab001-A:transfer]
[0000176F7A12A5164CF8978EB1BC89228EEF,25560690164] [Unknown]
<Unknown>:<Unknown>@osm 25560692880 930297 true
{NFS4-4.1:/131.169.72.192:1002}
[door:nfsv41@nfs:1378200573206-1378200573206] {100
11:"Transfer failed due to unexpected exception: Handle is closed"}

Pool Log:
03 Sep 2013 15:04:57 (dcache-lab001-A) [door:nfsv41@nfs:1378212562489
nfsv41 PoolAcceptFile 0000160E6F09995C4601966336EA2DFC2303] Transfer
failed in post-processing. Please report this bug to support@dcache.org.
java.lang.IllegalStateException: Handle is closed
 at
org.dcache.pool.repository.v5.WriteHandleImpl.close(WriteHandleImpl.java:377)
~[dcache-core-2.7.0-SNAPSHOT.jar:2.7.0-SNAPSHOT]
 at
org.dcache.pool.classic.DefaultPostTransferService$1.run(DefaultPostTransferService.java:108)
~[dcache-core-2.7.0-SNAPSHOT.jar:2.7.0-SNAPSHOT]
 at org.dcache.util.FireAndForgetTask.run(FireAndForgetTask.java:31)
~[dcache-core-2.7.0-SNAPSHOT.jar:2.7.0-SNAPSHOT]
 at
org.dcache.util.CDCExecutorServiceDecorator$1.run(CDCExecutorServiceDecorator.java:106)
~[dcache-core-2.7.0-SNAPSHOT.jar:2.7.0-SNAPSHOT]
 at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
~[na:1.7.0_25]
 at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
~[na:1.7.0_25]
 at java.lang.Thread.run(Thread.java:724) ~[na:1.7.0_25]

This patch changes the test to "cd" into the small files directory and
calling

  tar cf "${fullpath}.tar" *

This seems to work